module StripeAPI.Types.AccountCapabilityFutureRequirements where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountCapabilityFutureRequirements
instance Show AccountCapabilityFutureRequirements
instance Eq AccountCapabilityFutureRequirements
instance Data.Aeson.FromJSON AccountCapabilityFutureRequirements
instance Data.Aeson.ToJSON AccountCapabilityFutureRequirements
data AccountCapabilityFutureRequirementsDisabledReason'NonNullable
instance Show AccountCapabilityFutureRequirementsDisabledReason'NonNullable
instance Eq AccountCapabilityFutureRequirementsDisabledReason'NonNullable
instance Data.Aeson.FromJSON AccountCapabilityFutureRequirementsDisabledReason'NonNullable
instance Data.Aeson.ToJSON AccountCapabilityFutureRequirementsDisabledReason'NonNullable
