module StripeAPI.Types.BalanceAmountBySourceType where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BalanceAmountBySourceType
instance Show BalanceAmountBySourceType
instance Eq BalanceAmountBySourceType
instance Data.Aeson.FromJSON BalanceAmountBySourceType
instance Data.Aeson.ToJSON BalanceAmountBySourceType
