module StripeAPI.Types.BankConnectionsResourceBalanceApiResourceCashBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceBalanceApiResourceCashBalance
instance Show BankConnectionsResourceBalanceApiResourceCashBalance
instance Eq BankConnectionsResourceBalanceApiResourceCashBalance
instance Data.Aeson.FromJSON BankConnectionsResourceBalanceApiResourceCashBalance
instance Data.Aeson.ToJSON BankConnectionsResourceBalanceApiResourceCashBalance
