module StripeAPI.Types.BankConnectionsResourceBalanceRefresh where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceBalanceRefresh
instance Show BankConnectionsResourceBalanceRefresh
instance Eq BankConnectionsResourceBalanceRefresh
instance Data.Aeson.FromJSON BankConnectionsResourceBalanceRefresh
instance Data.Aeson.ToJSON BankConnectionsResourceBalanceRefresh
data BankConnectionsResourceBalanceRefreshStatus'
instance Show BankConnectionsResourceBalanceRefreshStatus'
instance Eq BankConnectionsResourceBalanceRefreshStatus'
instance Data.Aeson.FromJSON BankConnectionsResourceBalanceRefreshStatus'
instance Data.Aeson.ToJSON BankConnectionsResourceBalanceRefreshStatus'
