module StripeAPI.Types.BankConnectionsResourceTransactionResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceTransactionResourceStatusTransitions
instance Show BankConnectionsResourceTransactionResourceStatusTransitions
instance Eq BankConnectionsResourceTransactionResourceStatusTransitions
instance Data.Aeson.FromJSON BankConnectionsResourceTransactionResourceStatusTransitions
instance Data.Aeson.ToJSON BankConnectionsResourceTransactionResourceStatusTransitions
