module StripeAPI.Types.BankConnectionsResourceOwnershipRefresh where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceOwnershipRefresh
instance Show BankConnectionsResourceOwnershipRefresh
instance Eq BankConnectionsResourceOwnershipRefresh
instance Data.Aeson.FromJSON BankConnectionsResourceOwnershipRefresh
instance Data.Aeson.ToJSON BankConnectionsResourceOwnershipRefresh
data BankConnectionsResourceOwnershipRefreshStatus'
instance Show BankConnectionsResourceOwnershipRefreshStatus'
instance Eq BankConnectionsResourceOwnershipRefreshStatus'
instance Data.Aeson.FromJSON BankConnectionsResourceOwnershipRefreshStatus'
instance Data.Aeson.ToJSON BankConnectionsResourceOwnershipRefreshStatus'
