module StripeAPI.Types.BankConnectionsResourceLinkAccountSessionFilters where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceLinkAccountSessionFilters
instance Show BankConnectionsResourceLinkAccountSessionFilters
instance Eq BankConnectionsResourceLinkAccountSessionFilters
instance Data.Aeson.FromJSON BankConnectionsResourceLinkAccountSessionFilters
instance Data.Aeson.ToJSON BankConnectionsResourceLinkAccountSessionFilters
data BankConnectionsResourceLinkAccountSessionFiltersAccountSubcategories'NonNullable
instance Show BankConnectionsResourceLinkAccountSessionFiltersAccountSubcategories'NonNullable
instance Eq BankConnectionsResourceLinkAccountSessionFiltersAccountSubcategories'NonNullable
instance Data.Aeson.FromJSON BankConnectionsResourceLinkAccountSessionFiltersAccountSubcategories'NonNullable
instance Data.Aeson.ToJSON BankConnectionsResourceLinkAccountSessionFiltersAccountSubcategories'NonNullable
