module StripeAPI.Types.BankConnectionsResourceBalanceApiResourceCreditBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceBalanceApiResourceCreditBalance
instance Show BankConnectionsResourceBalanceApiResourceCreditBalance
instance Eq BankConnectionsResourceBalanceApiResourceCreditBalance
instance Data.Aeson.FromJSON BankConnectionsResourceBalanceApiResourceCreditBalance
instance Data.Aeson.ToJSON BankConnectionsResourceBalanceApiResourceCreditBalance
