module StripeAPI.Types.BankConnectionsResourceAccountholder where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceAccountholder
instance Show BankConnectionsResourceAccountholder
instance Eq BankConnectionsResourceAccountholder
instance Data.Aeson.FromJSON BankConnectionsResourceAccountholder
instance Data.Aeson.ToJSON BankConnectionsResourceAccountholder
data BankConnectionsResourceAccountholderAccount'Variants
instance Show BankConnectionsResourceAccountholderAccount'Variants
instance Eq BankConnectionsResourceAccountholderAccount'Variants
instance Data.Aeson.FromJSON BankConnectionsResourceAccountholderAccount'Variants
instance Data.Aeson.ToJSON BankConnectionsResourceAccountholderAccount'Variants
data BankConnectionsResourceAccountholderCustomer'Variants
instance Show BankConnectionsResourceAccountholderCustomer'Variants
instance Eq BankConnectionsResourceAccountholderCustomer'Variants
instance Data.Aeson.FromJSON BankConnectionsResourceAccountholderCustomer'Variants
instance Data.Aeson.ToJSON BankConnectionsResourceAccountholderCustomer'Variants
data BankConnectionsResourceAccountholderType'
instance Show BankConnectionsResourceAccountholderType'
instance Eq BankConnectionsResourceAccountholderType'
instance Data.Aeson.FromJSON BankConnectionsResourceAccountholderType'
instance Data.Aeson.ToJSON BankConnectionsResourceAccountholderType'
