module StripeAPI.Types.BankConnectionsResourceTransactionRefresh where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BankConnectionsResourceTransactionRefresh
instance Show BankConnectionsResourceTransactionRefresh
instance Eq BankConnectionsResourceTransactionRefresh
instance Data.Aeson.FromJSON BankConnectionsResourceTransactionRefresh
instance Data.Aeson.ToJSON BankConnectionsResourceTransactionRefresh
data BankConnectionsResourceTransactionRefreshStatus'
instance Show BankConnectionsResourceTransactionRefreshStatus'
instance Eq BankConnectionsResourceTransactionRefreshStatus'
instance Data.Aeson.FromJSON BankConnectionsResourceTransactionRefreshStatus'
instance Data.Aeson.ToJSON BankConnectionsResourceTransactionRefreshStatus'
