module StripeAPI.Types.BillingMeterResourceBillingMeterEventAdjustmentCancel where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingMeterResourceBillingMeterEventAdjustmentCancel
instance Show BillingMeterResourceBillingMeterEventAdjustmentCancel
instance Eq BillingMeterResourceBillingMeterEventAdjustmentCancel
instance Data.Aeson.FromJSON BillingMeterResourceBillingMeterEventAdjustmentCancel
instance Data.Aeson.ToJSON BillingMeterResourceBillingMeterEventAdjustmentCancel
