module StripeAPI.Types.BillingBillResourceInvoiceItemParentsInvoiceItemParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoiceItemParentsInvoiceItemParent
instance Show BillingBillResourceInvoiceItemParentsInvoiceItemParent
instance Eq BillingBillResourceInvoiceItemParentsInvoiceItemParent
instance Data.Aeson.FromJSON BillingBillResourceInvoiceItemParentsInvoiceItemParent
instance Data.Aeson.ToJSON BillingBillResourceInvoiceItemParentsInvoiceItemParent
data BillingBillResourceInvoiceItemParentsInvoiceItemParentSubscriptionDetails'NonNullable
instance Show BillingBillResourceInvoiceItemParentsInvoiceItemParentSubscriptionDetails'NonNullable
instance Eq BillingBillResourceInvoiceItemParentsInvoiceItemParentSubscriptionDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoiceItemParentsInvoiceItemParentSubscriptionDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoiceItemParentsInvoiceItemParentSubscriptionDetails'NonNullable
