-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema BillingMeterResourceBillingMeterValue
module StripeAPI.Types.BillingMeterResourceBillingMeterValue where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.billing_meter_resource_billing_meter_value@ in the specification.
-- 
-- 
data BillingMeterResourceBillingMeterValue = BillingMeterResourceBillingMeterValue {
  -- | event_payload_key: The key in the meter event payload to use as the value for this meter.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  billingMeterResourceBillingMeterValueEventPayloadKey :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON BillingMeterResourceBillingMeterValue
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["event_payload_key" Data.Aeson.Types.ToJSON..= billingMeterResourceBillingMeterValueEventPayloadKey obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["event_payload_key" Data.Aeson.Types.ToJSON..= billingMeterResourceBillingMeterValueEventPayloadKey obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON BillingMeterResourceBillingMeterValue
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingMeterResourceBillingMeterValue" (\obj -> GHC.Base.pure BillingMeterResourceBillingMeterValue GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "event_payload_key"))}
-- | Create a new 'BillingMeterResourceBillingMeterValue' with all required fields.
mkBillingMeterResourceBillingMeterValue :: Data.Text.Internal.Text -- ^ 'billingMeterResourceBillingMeterValueEventPayloadKey'
  -> BillingMeterResourceBillingMeterValue
mkBillingMeterResourceBillingMeterValue billingMeterResourceBillingMeterValueEventPayloadKey = BillingMeterResourceBillingMeterValue{billingMeterResourceBillingMeterValueEventPayloadKey = billingMeterResourceBillingMeterValueEventPayloadKey}
