module StripeAPI.Types.BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent
instance Show BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent
instance Eq BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent
instance Data.Aeson.FromJSON BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent
instance Data.Aeson.ToJSON BillingBillResourceInvoiceItemParentsInvoiceItemSubscriptionParent
