module StripeAPI.Types.ClimateRemovalsBeneficiary where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ClimateRemovalsBeneficiary
instance Show ClimateRemovalsBeneficiary
instance Eq ClimateRemovalsBeneficiary
instance Data.Aeson.FromJSON ClimateRemovalsBeneficiary
instance Data.Aeson.ToJSON ClimateRemovalsBeneficiary
