module StripeAPI.Types.ClimateRemovalsLocation where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ClimateRemovalsLocation
instance Show ClimateRemovalsLocation
instance Eq ClimateRemovalsLocation
instance Data.Aeson.FromJSON ClimateRemovalsLocation
instance Data.Aeson.ToJSON ClimateRemovalsLocation
