module StripeAPI.Types.ConfirmationTokensResourcePaymentMethodOptionsResourceCard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourcePaymentMethodOptionsResourceCard
instance Show ConfirmationTokensResourcePaymentMethodOptionsResourceCard
instance Eq ConfirmationTokensResourcePaymentMethodOptionsResourceCard
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodOptionsResourceCard
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodOptionsResourceCard
