module StripeAPI.Types.ConfirmationTokensResourceMandateDataResourceCustomerAcceptance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourceMandateDataResourceCustomerAcceptance
instance Show ConfirmationTokensResourceMandateDataResourceCustomerAcceptance
instance Eq ConfirmationTokensResourceMandateDataResourceCustomerAcceptance
instance Data.Aeson.FromJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptance
instance Data.Aeson.ToJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptance
data ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceOnline'NonNullable
instance Show ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceOnline'NonNullable
instance Eq ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceOnline'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceOnline'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceOnline'NonNullable
