module StripeAPI.Types.ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline
instance Show ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline
instance Eq ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline
instance Data.Aeson.FromJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline
instance Data.Aeson.ToJSON ConfirmationTokensResourceMandateDataResourceCustomerAcceptanceResourceOnline
