module StripeAPI.Types.ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment
instance Show ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment
instance Eq ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodOptionsResourceCardResourceInstallment
