module StripeAPI.Types.ConfirmationTokensResourcePaymentMethodPreview where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourcePaymentMethodPreview
instance Show ConfirmationTokensResourcePaymentMethodPreview
instance Eq ConfirmationTokensResourcePaymentMethodPreview
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodPreview
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodPreview
data ConfirmationTokensResourcePaymentMethodPreviewAllowRedisplay'
instance Show ConfirmationTokensResourcePaymentMethodPreviewAllowRedisplay'
instance Eq ConfirmationTokensResourcePaymentMethodPreviewAllowRedisplay'
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodPreviewAllowRedisplay'
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodPreviewAllowRedisplay'
data ConfirmationTokensResourcePaymentMethodPreviewCustomer'NonNullableVariants
instance Show ConfirmationTokensResourcePaymentMethodPreviewCustomer'NonNullableVariants
instance Eq ConfirmationTokensResourcePaymentMethodPreviewCustomer'NonNullableVariants
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodPreviewCustomer'NonNullableVariants
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodPreviewCustomer'NonNullableVariants
data ConfirmationTokensResourcePaymentMethodPreviewType'
instance Show ConfirmationTokensResourcePaymentMethodPreviewType'
instance Eq ConfirmationTokensResourcePaymentMethodPreviewType'
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodPreviewType'
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodPreviewType'
