module StripeAPI.Types.ConfirmationTokensResourcePaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationTokensResourcePaymentMethodOptions
instance Show ConfirmationTokensResourcePaymentMethodOptions
instance Eq ConfirmationTokensResourcePaymentMethodOptions
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodOptions
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodOptions
data ConfirmationTokensResourcePaymentMethodOptionsCard'NonNullable
instance Show ConfirmationTokensResourcePaymentMethodOptionsCard'NonNullable
instance Eq ConfirmationTokensResourcePaymentMethodOptionsCard'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokensResourcePaymentMethodOptionsCard'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokensResourcePaymentMethodOptionsCard'NonNullable
