module StripeAPI.Types.ConfirmationToken where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConfirmationToken
instance Show ConfirmationToken
instance Eq ConfirmationToken
instance Data.Aeson.FromJSON ConfirmationToken
instance Data.Aeson.ToJSON ConfirmationToken
data ConfirmationTokenMandateData'NonNullable
instance Show ConfirmationTokenMandateData'NonNullable
instance Eq ConfirmationTokenMandateData'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenMandateData'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenMandateData'NonNullable
data ConfirmationTokenPaymentMethodOptions'NonNullable
instance Show ConfirmationTokenPaymentMethodOptions'NonNullable
instance Eq ConfirmationTokenPaymentMethodOptions'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodOptions'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodOptions'NonNullable
data ConfirmationTokenPaymentMethodOptions'NonNullableCard'NonNullable
instance Show ConfirmationTokenPaymentMethodOptions'NonNullableCard'NonNullable
instance Eq ConfirmationTokenPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodOptions'NonNullableCard'NonNullable
data ConfirmationTokenPaymentMethodPreview'NonNullable
instance Show ConfirmationTokenPaymentMethodPreview'NonNullable
instance Eq ConfirmationTokenPaymentMethodPreview'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodPreview'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodPreview'NonNullable
data ConfirmationTokenPaymentMethodPreview'NonNullableAllowRedisplay'
instance Show ConfirmationTokenPaymentMethodPreview'NonNullableAllowRedisplay'
instance Eq ConfirmationTokenPaymentMethodPreview'NonNullableAllowRedisplay'
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodPreview'NonNullableAllowRedisplay'
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodPreview'NonNullableAllowRedisplay'
data ConfirmationTokenPaymentMethodPreview'NonNullableCustomer'NonNullableVariants
instance Show ConfirmationTokenPaymentMethodPreview'NonNullableCustomer'NonNullableVariants
instance Eq ConfirmationTokenPaymentMethodPreview'NonNullableCustomer'NonNullableVariants
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodPreview'NonNullableCustomer'NonNullableVariants
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodPreview'NonNullableCustomer'NonNullableVariants
data ConfirmationTokenPaymentMethodPreview'NonNullableType'
instance Show ConfirmationTokenPaymentMethodPreview'NonNullableType'
instance Eq ConfirmationTokenPaymentMethodPreview'NonNullableType'
instance Data.Aeson.FromJSON ConfirmationTokenPaymentMethodPreview'NonNullableType'
instance Data.Aeson.ToJSON ConfirmationTokenPaymentMethodPreview'NonNullableType'
data ConfirmationTokenSetupFutureUsage'NonNullable
instance Show ConfirmationTokenSetupFutureUsage'NonNullable
instance Eq ConfirmationTokenSetupFutureUsage'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenSetupFutureUsage'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenSetupFutureUsage'NonNullable
data ConfirmationTokenShipping'NonNullable
instance Show ConfirmationTokenShipping'NonNullable
instance Eq ConfirmationTokenShipping'NonNullable
instance Data.Aeson.FromJSON ConfirmationTokenShipping'NonNullable
instance Data.Aeson.ToJSON ConfirmationTokenShipping'NonNullable
