module StripeAPI.Types.ConnectEmbeddedPaymentsFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedPaymentsFeatures
instance Show ConnectEmbeddedPaymentsFeatures
instance Eq ConnectEmbeddedPaymentsFeatures
instance Data.Aeson.FromJSON ConnectEmbeddedPaymentsFeatures
instance Data.Aeson.ToJSON ConnectEmbeddedPaymentsFeatures
