module StripeAPI.Types.ConnectEmbeddedFinancialAccountTransactionsFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedFinancialAccountTransactionsFeatures
instance Show ConnectEmbeddedFinancialAccountTransactionsFeatures
instance Eq ConnectEmbeddedFinancialAccountTransactionsFeatures
instance Data.Aeson.FromJSON ConnectEmbeddedFinancialAccountTransactionsFeatures
instance Data.Aeson.ToJSON ConnectEmbeddedFinancialAccountTransactionsFeatures
