module StripeAPI.Types.ConnectEmbeddedFinancialAccountTransactionsConfigClaim where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedFinancialAccountTransactionsConfigClaim
instance Show ConnectEmbeddedFinancialAccountTransactionsConfigClaim
instance Eq ConnectEmbeddedFinancialAccountTransactionsConfigClaim
instance Data.Aeson.FromJSON ConnectEmbeddedFinancialAccountTransactionsConfigClaim
instance Data.Aeson.ToJSON ConnectEmbeddedFinancialAccountTransactionsConfigClaim
