-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ConnectEmbeddedFinancialAccountFeatures
module StripeAPI.Types.ConnectEmbeddedFinancialAccountFeatures where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.connect_embedded_financial_account_features@ in the specification.
-- 
-- 
data ConnectEmbeddedFinancialAccountFeatures = ConnectEmbeddedFinancialAccountFeatures {
  -- | disable_stripe_user_authentication: Whether Stripe user authentication is disabled. This value can only be \`true\` for accounts where \`controller.requirement_collection\` is \`application\` for the account. The default value is the opposite of the \`external_account_collection\` value. For example, if you don\'t set \`external_account_collection\`, it defaults to \`true\` and \`disable_stripe_user_authentication\` defaults to \`false\`.
  connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication :: GHC.Types.Bool
  -- | external_account_collection: Whether external account collection is enabled. This feature can only be \`false\` for accounts where you’re responsible for collecting updated information when requirements are due or change, like Custom accounts. The default value for this feature is \`true\`.
  , connectEmbeddedFinancialAccountFeaturesExternalAccountCollection :: GHC.Types.Bool
  -- | send_money: Whether to allow sending money.
  , connectEmbeddedFinancialAccountFeaturesSendMoney :: GHC.Types.Bool
  -- | transfer_balance: Whether to allow transferring balance.
  , connectEmbeddedFinancialAccountFeaturesTransferBalance :: GHC.Types.Bool
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ConnectEmbeddedFinancialAccountFeatures
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["disable_stripe_user_authentication" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication obj] : ["external_account_collection" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesExternalAccountCollection obj] : ["send_money" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesSendMoney obj] : ["transfer_balance" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesTransferBalance obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["disable_stripe_user_authentication" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication obj] : ["external_account_collection" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesExternalAccountCollection obj] : ["send_money" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesSendMoney obj] : ["transfer_balance" Data.Aeson.Types.ToJSON..= connectEmbeddedFinancialAccountFeaturesTransferBalance obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ConnectEmbeddedFinancialAccountFeatures
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ConnectEmbeddedFinancialAccountFeatures" (\obj -> (((GHC.Base.pure ConnectEmbeddedFinancialAccountFeatures GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "disable_stripe_user_authentication")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "external_account_collection")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "send_money")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "transfer_balance"))}
-- | Create a new 'ConnectEmbeddedFinancialAccountFeatures' with all required fields.
mkConnectEmbeddedFinancialAccountFeatures :: GHC.Types.Bool -- ^ 'connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication'
  -> GHC.Types.Bool -- ^ 'connectEmbeddedFinancialAccountFeaturesExternalAccountCollection'
  -> GHC.Types.Bool -- ^ 'connectEmbeddedFinancialAccountFeaturesSendMoney'
  -> GHC.Types.Bool -- ^ 'connectEmbeddedFinancialAccountFeaturesTransferBalance'
  -> ConnectEmbeddedFinancialAccountFeatures
mkConnectEmbeddedFinancialAccountFeatures connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication connectEmbeddedFinancialAccountFeaturesExternalAccountCollection connectEmbeddedFinancialAccountFeaturesSendMoney connectEmbeddedFinancialAccountFeaturesTransferBalance = ConnectEmbeddedFinancialAccountFeatures{connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication = connectEmbeddedFinancialAccountFeaturesDisableStripeUserAuthentication,
                                                                                                                                                                                                                                                                                                                                    connectEmbeddedFinancialAccountFeaturesExternalAccountCollection = connectEmbeddedFinancialAccountFeaturesExternalAccountCollection,
                                                                                                                                                                                                                                                                                                                                    connectEmbeddedFinancialAccountFeaturesSendMoney = connectEmbeddedFinancialAccountFeaturesSendMoney,
                                                                                                                                                                                                                                                                                                                                    connectEmbeddedFinancialAccountFeaturesTransferBalance = connectEmbeddedFinancialAccountFeaturesTransferBalance}
