module StripeAPI.Types.ConnectEmbeddedBaseConfigClaim where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedBaseConfigClaim
instance Show ConnectEmbeddedBaseConfigClaim
instance Eq ConnectEmbeddedBaseConfigClaim
instance Data.Aeson.FromJSON ConnectEmbeddedBaseConfigClaim
instance Data.Aeson.ToJSON ConnectEmbeddedBaseConfigClaim
