module StripeAPI.Types.ConnectEmbeddedPayoutsConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedPayoutsConfig
instance Show ConnectEmbeddedPayoutsConfig
instance Eq ConnectEmbeddedPayoutsConfig
instance Data.Aeson.FromJSON ConnectEmbeddedPayoutsConfig
instance Data.Aeson.ToJSON ConnectEmbeddedPayoutsConfig
