module StripeAPI.Types.ConnectEmbeddedPayoutsFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedPayoutsFeatures
instance Show ConnectEmbeddedPayoutsFeatures
instance Eq ConnectEmbeddedPayoutsFeatures
instance Data.Aeson.FromJSON ConnectEmbeddedPayoutsFeatures
instance Data.Aeson.ToJSON ConnectEmbeddedPayoutsFeatures
