module StripeAPI.Types.ConnectEmbeddedAccountSessionCreateComponents where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ConnectEmbeddedAccountSessionCreateComponents
instance Show ConnectEmbeddedAccountSessionCreateComponents
instance Eq ConnectEmbeddedAccountSessionCreateComponents
instance Data.Aeson.FromJSON ConnectEmbeddedAccountSessionCreateComponents
instance Data.Aeson.ToJSON ConnectEmbeddedAccountSessionCreateComponents
