module StripeAPI.Types.CountrySpecVerificationFields where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CountrySpecVerificationFields
instance Show CountrySpecVerificationFields
instance Eq CountrySpecVerificationFields
instance Data.Aeson.FromJSON CountrySpecVerificationFields
instance Data.Aeson.ToJSON CountrySpecVerificationFields
