module StripeAPI.Types.CountrySpecVerificationFieldDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CountrySpecVerificationFieldDetails
instance Show CountrySpecVerificationFieldDetails
instance Eq CountrySpecVerificationFieldDetails
instance Data.Aeson.FromJSON CountrySpecVerificationFieldDetails
instance Data.Aeson.ToJSON CountrySpecVerificationFieldDetails
