module StripeAPI.Types.CreditNotesPretaxCreditAmount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CreditNotesPretaxCreditAmount
instance Show CreditNotesPretaxCreditAmount
instance Eq CreditNotesPretaxCreditAmount
instance Data.Aeson.FromJSON CreditNotesPretaxCreditAmount
instance Data.Aeson.ToJSON CreditNotesPretaxCreditAmount
data CreditNotesPretaxCreditAmountCreditBalanceTransaction'Variants
instance Show CreditNotesPretaxCreditAmountCreditBalanceTransaction'Variants
instance Eq CreditNotesPretaxCreditAmountCreditBalanceTransaction'Variants
instance Data.Aeson.FromJSON CreditNotesPretaxCreditAmountCreditBalanceTransaction'Variants
instance Data.Aeson.ToJSON CreditNotesPretaxCreditAmountCreditBalanceTransaction'Variants
data CreditNotesPretaxCreditAmountDiscount'Variants
instance Show CreditNotesPretaxCreditAmountDiscount'Variants
instance Eq CreditNotesPretaxCreditAmountDiscount'Variants
instance Data.Aeson.FromJSON CreditNotesPretaxCreditAmountDiscount'Variants
instance Data.Aeson.ToJSON CreditNotesPretaxCreditAmountDiscount'Variants
data CreditNotesPretaxCreditAmountType'
instance Show CreditNotesPretaxCreditAmountType'
instance Eq CreditNotesPretaxCreditAmountType'
instance Data.Aeson.FromJSON CreditNotesPretaxCreditAmountType'
instance Data.Aeson.ToJSON CreditNotesPretaxCreditAmountType'
