-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CreditNoteLineItem
module StripeAPI.Types.CreditNoteLineItem where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingTaxesTax
import {-# SOURCE #-} StripeAPI.Types.CreditNotesPretaxCreditAmount
import {-# SOURCE #-} StripeAPI.Types.DiscountsResourceDiscountAmount
import {-# SOURCE #-} StripeAPI.Types.TaxRate

-- | Defines the object schema located at @components.schemas.credit_note_line_item@ in the specification.
-- 
-- The credit note line item object
data CreditNoteLineItem = CreditNoteLineItem {
  -- | amount: The integer amount in cents (or local equivalent) representing the gross amount being credited for this line item, excluding (exclusive) tax and discounts.
  creditNoteLineItemAmount :: GHC.Types.Int
  -- | description: Description of the item being credited.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , creditNoteLineItemDescription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  -- | discount_amount: The integer amount in cents (or local equivalent) representing the discount being credited for this line item.
  , creditNoteLineItemDiscountAmount :: GHC.Types.Int
  -- | discount_amounts: The amount of discount calculated per discount for this line item
  , creditNoteLineItemDiscountAmounts :: [DiscountsResourceDiscountAmount]
  -- | id: Unique identifier for the object.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , creditNoteLineItemId :: Data.Text.Internal.Text
  -- | invoice_line_item: ID of the invoice line item being credited
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , creditNoteLineItemInvoiceLineItem :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | livemode: Has the value \`true\` if the object exists in live mode or the value \`false\` if the object exists in test mode.
  , creditNoteLineItemLivemode :: GHC.Types.Bool
  -- | pretax_credit_amounts: The pretax credit amounts (ex: discount, credit grants, etc) for this line item.
  , creditNoteLineItemPretaxCreditAmounts :: [CreditNotesPretaxCreditAmount]
  -- | quantity: The number of units of product being credited.
  , creditNoteLineItemQuantity :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int))
  -- | tax_rates: The tax rates which apply to the line item.
  , creditNoteLineItemTaxRates :: [TaxRate]
  -- | taxes: The tax information of the line item.
  , creditNoteLineItemTaxes :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable [BillingBillResourceInvoicingTaxesTax]))
  -- | type: The type of the credit note line item, one of \`invoice_line_item\` or \`custom_line_item\`. When the type is \`invoice_line_item\` there is an additional \`invoice_line_item\` property on the resource the value of which is the id of the credited line item on the invoice.
  , creditNoteLineItemType :: CreditNoteLineItemType'
  -- | unit_amount: The cost of each unit of product being credited.
  , creditNoteLineItemUnitAmount :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int))
  -- | unit_amount_decimal: Same as \`unit_amount\`, but contains a decimal value with at most 12 decimal places.
  , creditNoteLineItemUnitAmountDecimal :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreditNoteLineItem
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= creditNoteLineItemAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemDescription obj) : ["discount_amount" Data.Aeson.Types.ToJSON..= creditNoteLineItemDiscountAmount obj] : ["discount_amounts" Data.Aeson.Types.ToJSON..= creditNoteLineItemDiscountAmounts obj] : ["id" Data.Aeson.Types.ToJSON..= creditNoteLineItemId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_item" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemInvoiceLineItem obj) : ["livemode" Data.Aeson.Types.ToJSON..= creditNoteLineItemLivemode obj] : ["pretax_credit_amounts" Data.Aeson.Types.ToJSON..= creditNoteLineItemPretaxCreditAmounts obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quantity" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemQuantity obj) : ["tax_rates" Data.Aeson.Types.ToJSON..= creditNoteLineItemTaxRates obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("taxes" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemTaxes obj) : ["type" Data.Aeson.Types.ToJSON..= creditNoteLineItemType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_amount" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemUnitAmount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_amount_decimal" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemUnitAmountDecimal obj) : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "credit_note_line_item"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= creditNoteLineItemAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("description" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemDescription obj) : ["discount_amount" Data.Aeson.Types.ToJSON..= creditNoteLineItemDiscountAmount obj] : ["discount_amounts" Data.Aeson.Types.ToJSON..= creditNoteLineItemDiscountAmounts obj] : ["id" Data.Aeson.Types.ToJSON..= creditNoteLineItemId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_item" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemInvoiceLineItem obj) : ["livemode" Data.Aeson.Types.ToJSON..= creditNoteLineItemLivemode obj] : ["pretax_credit_amounts" Data.Aeson.Types.ToJSON..= creditNoteLineItemPretaxCreditAmounts obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quantity" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemQuantity obj) : ["tax_rates" Data.Aeson.Types.ToJSON..= creditNoteLineItemTaxRates obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("taxes" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemTaxes obj) : ["type" Data.Aeson.Types.ToJSON..= creditNoteLineItemType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_amount" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemUnitAmount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_amount_decimal" Data.Aeson.Types.ToJSON..=)) (creditNoteLineItemUnitAmountDecimal obj) : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "credit_note_line_item"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON CreditNoteLineItem
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "CreditNoteLineItem" (\obj -> (((((((((((((GHC.Base.pure CreditNoteLineItem GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "description")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "discount_amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "discount_amounts")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_line_item")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "livemode")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pretax_credit_amounts")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "quantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "tax_rates")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "taxes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "unit_amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "unit_amount_decimal"))}
-- | Create a new 'CreditNoteLineItem' with all required fields.
mkCreditNoteLineItem :: GHC.Types.Int -- ^ 'creditNoteLineItemAmount'
  -> GHC.Types.Int -- ^ 'creditNoteLineItemDiscountAmount'
  -> [DiscountsResourceDiscountAmount] -- ^ 'creditNoteLineItemDiscountAmounts'
  -> Data.Text.Internal.Text -- ^ 'creditNoteLineItemId'
  -> GHC.Types.Bool -- ^ 'creditNoteLineItemLivemode'
  -> [CreditNotesPretaxCreditAmount] -- ^ 'creditNoteLineItemPretaxCreditAmounts'
  -> [TaxRate] -- ^ 'creditNoteLineItemTaxRates'
  -> CreditNoteLineItemType' -- ^ 'creditNoteLineItemType'
  -> CreditNoteLineItem
mkCreditNoteLineItem creditNoteLineItemAmount creditNoteLineItemDiscountAmount creditNoteLineItemDiscountAmounts creditNoteLineItemId creditNoteLineItemLivemode creditNoteLineItemPretaxCreditAmounts creditNoteLineItemTaxRates creditNoteLineItemType = CreditNoteLineItem{creditNoteLineItemAmount = creditNoteLineItemAmount,
                                                                                                                                                                                                                                                                              creditNoteLineItemDescription = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                              creditNoteLineItemDiscountAmount = creditNoteLineItemDiscountAmount,
                                                                                                                                                                                                                                                                              creditNoteLineItemDiscountAmounts = creditNoteLineItemDiscountAmounts,
                                                                                                                                                                                                                                                                              creditNoteLineItemId = creditNoteLineItemId,
                                                                                                                                                                                                                                                                              creditNoteLineItemInvoiceLineItem = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                              creditNoteLineItemLivemode = creditNoteLineItemLivemode,
                                                                                                                                                                                                                                                                              creditNoteLineItemPretaxCreditAmounts = creditNoteLineItemPretaxCreditAmounts,
                                                                                                                                                                                                                                                                              creditNoteLineItemQuantity = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                              creditNoteLineItemTaxRates = creditNoteLineItemTaxRates,
                                                                                                                                                                                                                                                                              creditNoteLineItemTaxes = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                              creditNoteLineItemType = creditNoteLineItemType,
                                                                                                                                                                                                                                                                              creditNoteLineItemUnitAmount = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                              creditNoteLineItemUnitAmountDecimal = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.credit_note_line_item.properties.type@ in the specification.
-- 
-- The type of the credit note line item, one of \`invoice_line_item\` or \`custom_line_item\`. When the type is \`invoice_line_item\` there is an additional \`invoice_line_item\` property on the resource the value of which is the id of the credited line item on the invoice.
data CreditNoteLineItemType' =
   CreditNoteLineItemType'Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | CreditNoteLineItemType'Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | CreditNoteLineItemType'EnumCustomLineItem -- ^ Represents the JSON value @"custom_line_item"@
  | CreditNoteLineItemType'EnumInvoiceLineItem -- ^ Represents the JSON value @"invoice_line_item"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreditNoteLineItemType'
    where {toJSON (CreditNoteLineItemType'Other val) = val;
           toJSON (CreditNoteLineItemType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (CreditNoteLineItemType'EnumCustomLineItem) = "custom_line_item";
           toJSON (CreditNoteLineItemType'EnumInvoiceLineItem) = "invoice_line_item"}
instance Data.Aeson.Types.FromJSON.FromJSON CreditNoteLineItemType'
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "custom_line_item" -> CreditNoteLineItemType'EnumCustomLineItem
                                             | val GHC.Classes.== "invoice_line_item" -> CreditNoteLineItemType'EnumInvoiceLineItem
                                             | GHC.Base.otherwise -> CreditNoteLineItemType'Other val)}
