module StripeAPI.Types.CustomerSessionResourceComponentsResourcePricingTable where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerSessionResourceComponentsResourcePricingTable
instance Show CustomerSessionResourceComponentsResourcePricingTable
instance Eq CustomerSessionResourceComponentsResourcePricingTable
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePricingTable
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePricingTable
