module StripeAPI.Types.CustomerSessionResourceComponentsResourcePaymentElement where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerSessionResourceComponentsResourcePaymentElement
instance Show CustomerSessionResourceComponentsResourcePaymentElement
instance Eq CustomerSessionResourceComponentsResourcePaymentElement
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElement
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElement
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullable
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullable
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullable
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullable
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullable
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodAllowRedisplayFilters'
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodAllowRedisplayFilters'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodAllowRedisplayFilters'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodAllowRedisplayFilters'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodAllowRedisplayFilters'
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRedisplay'
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRedisplay'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRedisplay'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRedisplay'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRedisplay'
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRemove'
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRemove'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRemove'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRemove'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodRemove'
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSave'
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSave'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSave'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSave'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSave'
data CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSaveUsage'NonNullable
instance Show CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSaveUsage'NonNullable
instance Eq CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSaveUsage'NonNullable
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSaveUsage'NonNullable
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementFeatures'NonNullablePaymentMethodSaveUsage'NonNullable
