module StripeAPI.Types.CustomerBalanceTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceTransaction
instance Show CustomerBalanceTransaction
instance Eq CustomerBalanceTransaction
instance Data.Aeson.FromJSON CustomerBalanceTransaction
instance Data.Aeson.ToJSON CustomerBalanceTransaction
data CustomerBalanceTransactionCheckoutSession'NonNullableVariants
instance Show CustomerBalanceTransactionCheckoutSession'NonNullableVariants
instance Eq CustomerBalanceTransactionCheckoutSession'NonNullableVariants
instance Data.Aeson.FromJSON CustomerBalanceTransactionCheckoutSession'NonNullableVariants
instance Data.Aeson.ToJSON CustomerBalanceTransactionCheckoutSession'NonNullableVariants
data CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Show CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Eq CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Data.Aeson.FromJSON CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Data.Aeson.ToJSON CustomerBalanceTransactionCreditNote'NonNullableVariants
data CustomerBalanceTransactionCustomer'Variants
instance Show CustomerBalanceTransactionCustomer'Variants
instance Eq CustomerBalanceTransactionCustomer'Variants
instance Data.Aeson.FromJSON CustomerBalanceTransactionCustomer'Variants
instance Data.Aeson.ToJSON CustomerBalanceTransactionCustomer'Variants
data CustomerBalanceTransactionInvoice'NonNullableVariants
instance Show CustomerBalanceTransactionInvoice'NonNullableVariants
instance Eq CustomerBalanceTransactionInvoice'NonNullableVariants
instance Data.Aeson.FromJSON CustomerBalanceTransactionInvoice'NonNullableVariants
instance Data.Aeson.ToJSON CustomerBalanceTransactionInvoice'NonNullableVariants
data CustomerBalanceTransactionType'
instance Show CustomerBalanceTransactionType'
instance Eq CustomerBalanceTransactionType'
instance Data.Aeson.FromJSON CustomerBalanceTransactionType'
instance Data.Aeson.ToJSON CustomerBalanceTransactionType'
