module StripeAPI.Types.CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodAllowRedisplayFilters'
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodAllowRedisplayFilters'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodAllowRedisplayFilters'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodAllowRedisplayFilters'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodAllowRedisplayFilters'
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRedisplay'
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRedisplay'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRedisplay'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRedisplay'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRedisplay'
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRemove'
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRemove'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRemove'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRemove'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodRemove'
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSave'
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSave'
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSave'
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSave'
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSave'
data CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSaveUsage'NonNullable
instance Show CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSaveUsage'NonNullable
instance Eq CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSaveUsage'NonNullable
instance Data.Aeson.FromJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSaveUsage'NonNullable
instance Data.Aeson.ToJSON CustomerSessionResourceComponentsResourcePaymentElementResourceFeaturesPaymentMethodSaveUsage'NonNullable
