module StripeAPI.Types.DeletedApplePayDomain where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DeletedApplePayDomain
instance Show DeletedApplePayDomain
instance Eq DeletedApplePayDomain
instance Data.Aeson.FromJSON DeletedApplePayDomain
instance Data.Aeson.ToJSON DeletedApplePayDomain
