module StripeAPI.Types.DeletedWebhookEndpoint where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DeletedWebhookEndpoint
instance Show DeletedWebhookEndpoint
instance Eq DeletedWebhookEndpoint
instance Data.Aeson.FromJSON DeletedWebhookEndpoint
instance Data.Aeson.ToJSON DeletedWebhookEndpoint
