module StripeAPI.Types.DeletedSubscriptionItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DeletedSubscriptionItem
instance Show DeletedSubscriptionItem
instance Eq DeletedSubscriptionItem
instance Data.Aeson.FromJSON DeletedSubscriptionItem
instance Data.Aeson.ToJSON DeletedSubscriptionItem
