module StripeAPI.Types.FinancialReportingFinanceReportRunRunParameters where
import qualified Data.Aeson
import qualified StripeAPI.Common
data FinancialReportingFinanceReportRunRunParameters
instance Show FinancialReportingFinanceReportRunRunParameters
instance Eq FinancialReportingFinanceReportRunRunParameters
instance Data.Aeson.FromJSON FinancialReportingFinanceReportRunRunParameters
instance Data.Aeson.ToJSON FinancialReportingFinanceReportRunRunParameters
