module StripeAPI.Types.FinancialConnections_AccountOwner where
import qualified Data.Aeson
import qualified StripeAPI.Common
data FinancialConnections'accountOwner
instance Show FinancialConnections'accountOwner
instance Eq FinancialConnections'accountOwner
instance Data.Aeson.FromJSON FinancialConnections'accountOwner
instance Data.Aeson.ToJSON FinancialConnections'accountOwner
