module StripeAPI.Types.GelatoDataDocumentReportExpirationDate where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoDataDocumentReportExpirationDate
instance Show GelatoDataDocumentReportExpirationDate
instance Eq GelatoDataDocumentReportExpirationDate
instance Data.Aeson.FromJSON GelatoDataDocumentReportExpirationDate
instance Data.Aeson.ToJSON GelatoDataDocumentReportExpirationDate
