module StripeAPI.Types.GelatoVerificationReportOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoVerificationReportOptions
instance Show GelatoVerificationReportOptions
instance Eq GelatoVerificationReportOptions
instance Data.Aeson.FromJSON GelatoVerificationReportOptions
instance Data.Aeson.ToJSON GelatoVerificationReportOptions
