module StripeAPI.Types.GelatoSessionDocumentOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoSessionDocumentOptions
instance Show GelatoSessionDocumentOptions
instance Eq GelatoSessionDocumentOptions
instance Data.Aeson.FromJSON GelatoSessionDocumentOptions
instance Data.Aeson.ToJSON GelatoSessionDocumentOptions
data GelatoSessionDocumentOptionsAllowedTypes'
instance Show GelatoSessionDocumentOptionsAllowedTypes'
instance Eq GelatoSessionDocumentOptionsAllowedTypes'
instance Data.Aeson.FromJSON GelatoSessionDocumentOptionsAllowedTypes'
instance Data.Aeson.ToJSON GelatoSessionDocumentOptionsAllowedTypes'
