module StripeAPI.Types.GelatoReportDocumentOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoReportDocumentOptions
instance Show GelatoReportDocumentOptions
instance Eq GelatoReportDocumentOptions
instance Data.Aeson.FromJSON GelatoReportDocumentOptions
instance Data.Aeson.ToJSON GelatoReportDocumentOptions
data GelatoReportDocumentOptionsAllowedTypes'
instance Show GelatoReportDocumentOptionsAllowedTypes'
instance Eq GelatoReportDocumentOptionsAllowedTypes'
instance Data.Aeson.FromJSON GelatoReportDocumentOptionsAllowedTypes'
instance Data.Aeson.ToJSON GelatoReportDocumentOptionsAllowedTypes'
