module StripeAPI.Types.GelatoDataVerifiedOutputsDate where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoDataVerifiedOutputsDate
instance Show GelatoDataVerifiedOutputsDate
instance Eq GelatoDataVerifiedOutputsDate
instance Data.Aeson.FromJSON GelatoDataVerifiedOutputsDate
instance Data.Aeson.ToJSON GelatoDataVerifiedOutputsDate
