module StripeAPI.Types.GelatoDataDocumentReportDateOfBirth where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoDataDocumentReportDateOfBirth
instance Show GelatoDataDocumentReportDateOfBirth
instance Eq GelatoDataDocumentReportDateOfBirth
instance Data.Aeson.FromJSON GelatoDataDocumentReportDateOfBirth
instance Data.Aeson.ToJSON GelatoDataDocumentReportDateOfBirth
