module StripeAPI.Types.GelatoDataDocumentReportIssuedDate where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoDataDocumentReportIssuedDate
instance Show GelatoDataDocumentReportIssuedDate
instance Eq GelatoDataDocumentReportIssuedDate
instance Data.Aeson.FromJSON GelatoDataDocumentReportIssuedDate
instance Data.Aeson.ToJSON GelatoDataDocumentReportIssuedDate
