module StripeAPI.Types.GelatoDataIdNumberReportDate where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoDataIdNumberReportDate
instance Show GelatoDataIdNumberReportDate
instance Eq GelatoDataIdNumberReportDate
instance Data.Aeson.FromJSON GelatoDataIdNumberReportDate
instance Data.Aeson.ToJSON GelatoDataIdNumberReportDate
