module StripeAPI.Types.GelatoVerificationSessionOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data GelatoVerificationSessionOptions
instance Show GelatoVerificationSessionOptions
instance Eq GelatoVerificationSessionOptions
instance Data.Aeson.FromJSON GelatoVerificationSessionOptions
instance Data.Aeson.ToJSON GelatoVerificationSessionOptions
