module StripeAPI.Types.InboundTransfersPaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InboundTransfersPaymentMethodDetailsUsBankAccount
instance Show InboundTransfersPaymentMethodDetailsUsBankAccount
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccount
instance Data.Aeson.FromJSON InboundTransfersPaymentMethodDetailsUsBankAccount
instance Data.Aeson.ToJSON InboundTransfersPaymentMethodDetailsUsBankAccount
data InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.FromJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.ToJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.FromJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.ToJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
data InboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Show InboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.FromJSON InboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.ToJSON InboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
