module StripeAPI.Types.InvoiceSettingQuoteSetting where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoiceSettingQuoteSetting
instance Show InvoiceSettingQuoteSetting
instance Eq InvoiceSettingQuoteSetting
instance Data.Aeson.FromJSON InvoiceSettingQuoteSetting
instance Data.Aeson.ToJSON InvoiceSettingQuoteSetting
