module StripeAPI.Types.NotificationEventRequest where
import qualified Data.Aeson
import qualified StripeAPI.Common
data NotificationEventRequest
instance Show NotificationEventRequest
instance Eq NotificationEventRequest
instance Data.Aeson.FromJSON NotificationEventRequest
instance Data.Aeson.ToJSON NotificationEventRequest
