module StripeAPI.Types.NotificationEventData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data NotificationEventData
instance Show NotificationEventData
instance Eq NotificationEventData
instance Data.Aeson.FromJSON NotificationEventData
instance Data.Aeson.ToJSON NotificationEventData
