module StripeAPI.Types.OutboundTransfersPaymentMethodDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundTransfersPaymentMethodDetails
instance Show OutboundTransfersPaymentMethodDetails
instance Eq OutboundTransfersPaymentMethodDetails
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetails
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetails
data OutboundTransfersPaymentMethodDetailsType'
instance Show OutboundTransfersPaymentMethodDetailsType'
instance Eq OutboundTransfersPaymentMethodDetailsType'
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsType'
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsType'
