module StripeAPI.Types.OutboundPaymentsPaymentMethodDetailsFinancialAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundPaymentsPaymentMethodDetailsFinancialAccount
instance Show OutboundPaymentsPaymentMethodDetailsFinancialAccount
instance Eq OutboundPaymentsPaymentMethodDetailsFinancialAccount
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsFinancialAccount
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsFinancialAccount
