module StripeAPI.Types.OutboundTransfersPaymentMethodDetailsFinancialAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundTransfersPaymentMethodDetailsFinancialAccount
instance Show OutboundTransfersPaymentMethodDetailsFinancialAccount
instance Eq OutboundTransfersPaymentMethodDetailsFinancialAccount
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsFinancialAccount
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsFinancialAccount
