module StripeAPI.Types.OutboundTransfersPaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccount
data OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
data OutboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountMandate'Variants
data OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Data.Aeson.FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Data.Aeson.ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
