module StripeAPI.Types.OutboundPaymentsPaymentMethodDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundPaymentsPaymentMethodDetails
instance Show OutboundPaymentsPaymentMethodDetails
instance Eq OutboundPaymentsPaymentMethodDetails
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetails
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetails
data OutboundPaymentsPaymentMethodDetailsType'
instance Show OutboundPaymentsPaymentMethodDetailsType'
instance Eq OutboundPaymentsPaymentMethodDetailsType'
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsType'
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsType'
