module StripeAPI.Types.OutboundPaymentsPaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccount
data OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
data OutboundPaymentsPaymentMethodDetailsUsBankAccountMandate'Variants
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountMandate'Variants
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountMandate'Variants
data OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Data.Aeson.FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Data.Aeson.ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
