module StripeAPI.Types.PaymentMethodConfiguration where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodConfiguration
instance Show PaymentMethodConfiguration
instance Eq PaymentMethodConfiguration
instance Data.Aeson.FromJSON PaymentMethodConfiguration
instance Data.Aeson.ToJSON PaymentMethodConfiguration
