module StripeAPI.Types.PaymentMethodDomainResourcePaymentMethodStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDomainResourcePaymentMethodStatusDetails
instance Show PaymentMethodDomainResourcePaymentMethodStatusDetails
instance Eq PaymentMethodDomainResourcePaymentMethodStatusDetails
instance Data.Aeson.FromJSON PaymentMethodDomainResourcePaymentMethodStatusDetails
instance Data.Aeson.ToJSON PaymentMethodDomainResourcePaymentMethodStatusDetails
