module StripeAPI.Types.PaymentMethodDomainResourcePaymentMethodStatus where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDomainResourcePaymentMethodStatus
instance Show PaymentMethodDomainResourcePaymentMethodStatus
instance Eq PaymentMethodDomainResourcePaymentMethodStatus
instance Data.Aeson.FromJSON PaymentMethodDomainResourcePaymentMethodStatus
instance Data.Aeson.ToJSON PaymentMethodDomainResourcePaymentMethodStatus
data PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Show PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Eq PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Data.Aeson.FromJSON PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Data.Aeson.ToJSON PaymentMethodDomainResourcePaymentMethodStatusStatus'
