module StripeAPI.Types.PaymentMethodConfigResourcePaymentMethodProperties where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodConfigResourcePaymentMethodProperties
instance Show PaymentMethodConfigResourcePaymentMethodProperties
instance Eq PaymentMethodConfigResourcePaymentMethodProperties
instance Data.Aeson.FromJSON PaymentMethodConfigResourcePaymentMethodProperties
instance Data.Aeson.ToJSON PaymentMethodConfigResourcePaymentMethodProperties
