module StripeAPI.Types.PaymentMethodConfigResourceDisplayPreference where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodConfigResourceDisplayPreference
instance Show PaymentMethodConfigResourceDisplayPreference
instance Eq PaymentMethodConfigResourceDisplayPreference
instance Data.Aeson.FromJSON PaymentMethodConfigResourceDisplayPreference
instance Data.Aeson.ToJSON PaymentMethodConfigResourceDisplayPreference
data PaymentMethodConfigResourceDisplayPreferencePreference'
instance Show PaymentMethodConfigResourceDisplayPreferencePreference'
instance Eq PaymentMethodConfigResourceDisplayPreferencePreference'
instance Data.Aeson.FromJSON PaymentMethodConfigResourceDisplayPreferencePreference'
instance Data.Aeson.ToJSON PaymentMethodConfigResourceDisplayPreferencePreference'
data PaymentMethodConfigResourceDisplayPreferenceValue'
instance Show PaymentMethodConfigResourceDisplayPreferenceValue'
instance Eq PaymentMethodConfigResourceDisplayPreferenceValue'
instance Data.Aeson.FromJSON PaymentMethodConfigResourceDisplayPreferenceValue'
instance Data.Aeson.ToJSON PaymentMethodConfigResourceDisplayPreferenceValue'
