module StripeAPI.Types.QuotesResourceTotalDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data QuotesResourceTotalDetails
instance Show QuotesResourceTotalDetails
instance Eq QuotesResourceTotalDetails
instance Data.Aeson.FromJSON QuotesResourceTotalDetails
instance Data.Aeson.ToJSON QuotesResourceTotalDetails
