module StripeAPI.Types.QuotesResourceAutomaticTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data QuotesResourceAutomaticTax
instance Show QuotesResourceAutomaticTax
instance Eq QuotesResourceAutomaticTax
instance Data.Aeson.FromJSON QuotesResourceAutomaticTax
instance Data.Aeson.ToJSON QuotesResourceAutomaticTax
data QuotesResourceAutomaticTaxLiability'NonNullable
instance Show QuotesResourceAutomaticTaxLiability'NonNullable
instance Eq QuotesResourceAutomaticTaxLiability'NonNullable
instance Data.Aeson.FromJSON QuotesResourceAutomaticTaxLiability'NonNullable
instance Data.Aeson.ToJSON QuotesResourceAutomaticTaxLiability'NonNullable
data QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Show QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.FromJSON QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.ToJSON QuotesResourceAutomaticTaxLiability'NonNullableAccount'Variants
data QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Show QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Eq QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.FromJSON QuotesResourceAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.ToJSON QuotesResourceAutomaticTaxLiability'NonNullableType'
data QuotesResourceAutomaticTaxStatus'NonNullable
instance Show QuotesResourceAutomaticTaxStatus'NonNullable
instance Eq QuotesResourceAutomaticTaxStatus'NonNullable
instance Data.Aeson.FromJSON QuotesResourceAutomaticTaxStatus'NonNullable
instance Data.Aeson.ToJSON QuotesResourceAutomaticTaxStatus'NonNullable
