module StripeAPI.Types.QuotesResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data QuotesResourceStatusTransitions
instance Show QuotesResourceStatusTransitions
instance Eq QuotesResourceStatusTransitions
instance Data.Aeson.FromJSON QuotesResourceStatusTransitions
instance Data.Aeson.ToJSON QuotesResourceStatusTransitions
