module StripeAPI.Types.QuotesResourceTotalDetailsResourceBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data QuotesResourceTotalDetailsResourceBreakdown
instance Show QuotesResourceTotalDetailsResourceBreakdown
instance Eq QuotesResourceTotalDetailsResourceBreakdown
instance Data.Aeson.FromJSON QuotesResourceTotalDetailsResourceBreakdown
instance Data.Aeson.ToJSON QuotesResourceTotalDetailsResourceBreakdown
