module StripeAPI.Types.QuotesResourceSubscriptionDataSubscriptionData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data QuotesResourceSubscriptionDataSubscriptionData
instance Show QuotesResourceSubscriptionDataSubscriptionData
instance Eq QuotesResourceSubscriptionDataSubscriptionData
instance Data.Aeson.FromJSON QuotesResourceSubscriptionDataSubscriptionData
instance Data.Aeson.ToJSON QuotesResourceSubscriptionDataSubscriptionData
