module StripeAPI.Types.ReceivedPaymentMethodDetailsFinancialAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ReceivedPaymentMethodDetailsFinancialAccount
instance Show ReceivedPaymentMethodDetailsFinancialAccount
instance Eq ReceivedPaymentMethodDetailsFinancialAccount
instance Data.Aeson.FromJSON ReceivedPaymentMethodDetailsFinancialAccount
instance Data.Aeson.ToJSON ReceivedPaymentMethodDetailsFinancialAccount
