module StripeAPI.Types.SigmaScheduledQueryRunError where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SigmaScheduledQueryRunError
instance Show SigmaScheduledQueryRunError
instance Eq SigmaScheduledQueryRunError
instance Data.Aeson.FromJSON SigmaScheduledQueryRunError
instance Data.Aeson.ToJSON SigmaScheduledQueryRunError
