module StripeAPI.Types.SourceMandateNotificationBacsDebitData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceMandateNotificationBacsDebitData
instance Show SourceMandateNotificationBacsDebitData
instance Eq SourceMandateNotificationBacsDebitData
instance Data.Aeson.FromJSON SourceMandateNotificationBacsDebitData
instance Data.Aeson.ToJSON SourceMandateNotificationBacsDebitData
