module StripeAPI.Types.SourceTransactionPaperCheckData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceTransactionPaperCheckData
instance Show SourceTransactionPaperCheckData
instance Eq SourceTransactionPaperCheckData
instance Data.Aeson.FromJSON SourceTransactionPaperCheckData
instance Data.Aeson.ToJSON SourceTransactionPaperCheckData
