module StripeAPI.Types.SourceMandateNotificationAcssDebitData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceMandateNotificationAcssDebitData
instance Show SourceMandateNotificationAcssDebitData
instance Eq SourceMandateNotificationAcssDebitData
instance Data.Aeson.FromJSON SourceMandateNotificationAcssDebitData
instance Data.Aeson.ToJSON SourceMandateNotificationAcssDebitData
