module StripeAPI.Types.SourceMandateNotificationSepaDebitData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceMandateNotificationSepaDebitData
instance Show SourceMandateNotificationSepaDebitData
instance Eq SourceMandateNotificationSepaDebitData
instance Data.Aeson.FromJSON SourceMandateNotificationSepaDebitData
instance Data.Aeson.ToJSON SourceMandateNotificationSepaDebitData
