module StripeAPI.Types.SourceTransactionGbpCreditTransferData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceTransactionGbpCreditTransferData
instance Show SourceTransactionGbpCreditTransferData
instance Eq SourceTransactionGbpCreditTransferData
instance Data.Aeson.FromJSON SourceTransactionGbpCreditTransferData
instance Data.Aeson.ToJSON SourceTransactionGbpCreditTransferData
