module StripeAPI.Types.SourceTransactionAchCreditTransferData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceTransactionAchCreditTransferData
instance Show SourceTransactionAchCreditTransferData
instance Eq SourceTransactionAchCreditTransferData
instance Data.Aeson.FromJSON SourceTransactionAchCreditTransferData
instance Data.Aeson.ToJSON SourceTransactionAchCreditTransferData
