module StripeAPI.Types.SourceTransactionChfCreditTransferData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceTransactionChfCreditTransferData
instance Show SourceTransactionChfCreditTransferData
instance Eq SourceTransactionChfCreditTransferData
instance Data.Aeson.FromJSON SourceTransactionChfCreditTransferData
instance Data.Aeson.ToJSON SourceTransactionChfCreditTransferData
