module StripeAPI.Types.SourceMandateNotification where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceMandateNotification
instance Show SourceMandateNotification
instance Eq SourceMandateNotification
instance Data.Aeson.FromJSON SourceMandateNotification
instance Data.Aeson.ToJSON SourceMandateNotification
