module StripeAPI.Types.SourceTransactionSepaCreditTransferData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SourceTransactionSepaCreditTransferData
instance Show SourceTransactionSepaCreditTransferData
instance Eq SourceTransactionSepaCreditTransferData
instance Data.Aeson.FromJSON SourceTransactionSepaCreditTransferData
instance Data.Aeson.ToJSON SourceTransactionSepaCreditTransferData
