module StripeAPI.Types.TaxProductResourcePostalAddress where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourcePostalAddress
instance Show TaxProductResourcePostalAddress
instance Eq TaxProductResourcePostalAddress
instance Data.Aeson.FromJSON TaxProductResourcePostalAddress
instance Data.Aeson.ToJSON TaxProductResourcePostalAddress
