module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Show TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Eq TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
