module StripeAPI.Types.TaxProductResourceCustomerDetailsResourceTaxId where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceCustomerDetailsResourceTaxId
instance Show TaxProductResourceCustomerDetailsResourceTaxId
instance Eq TaxProductResourceCustomerDetailsResourceTaxId
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetailsResourceTaxId
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetailsResourceTaxId
data TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Show TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Eq TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetailsResourceTaxIdType'
