module StripeAPI.Types.TaxProductResourceLineItemTaxBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceLineItemTaxBreakdown
instance Show TaxProductResourceLineItemTaxBreakdown
instance Eq TaxProductResourceLineItemTaxBreakdown
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxBreakdown
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxBreakdown
data TaxProductResourceLineItemTaxBreakdownSourcing'
instance Show TaxProductResourceLineItemTaxBreakdownSourcing'
instance Eq TaxProductResourceLineItemTaxBreakdownSourcing'
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxBreakdownSourcing'
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxBreakdownSourcing'
data TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Show TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Eq TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
data TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Show TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Eq TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
data TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Show TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Eq TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
