module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods
instance Show TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods
instance Eq TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsDefaultInboundGoods
