module StripeAPI.Types.TaxProductResourceTaxTransactionLineItemResourceReversal where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionLineItemResourceReversal
instance Show TaxProductResourceTaxTransactionLineItemResourceReversal
instance Eq TaxProductResourceTaxTransactionLineItemResourceReversal
instance Data.Aeson.FromJSON TaxProductResourceTaxTransactionLineItemResourceReversal
instance Data.Aeson.ToJSON TaxProductResourceTaxTransactionLineItemResourceReversal
