-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection

-- | Defines the object schema located at @components.schemas.tax_product_registrations_resource_country_options_us_state_sales_tax@ in the specification.
-- 
-- 
data TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax = TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax {
  -- | elections: Elections for the state sales tax registration.
  taxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElections :: (GHC.Maybe.Maybe [TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection])
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("elections" Data.Aeson.Types.ToJSON..=)) (taxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElections obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("elections" Data.Aeson.Types.ToJSON..=)) (taxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElections obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax" (\obj -> GHC.Base.pure TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "elections"))}
-- | Create a new 'TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax' with all required fields.
mkTaxProductRegistrationsResourceCountryOptionsUsStateSalesTax :: TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
mkTaxProductRegistrationsResourceCountryOptionsUsStateSalesTax = TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax{taxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElections = GHC.Maybe.Nothing}
