module StripeAPI.Types.TaxProductResourceTaxRateDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxRateDetails
instance Show TaxProductResourceTaxRateDetails
instance Eq TaxProductResourceTaxRateDetails
instance Data.Aeson.FromJSON TaxProductResourceTaxRateDetails
instance Data.Aeson.ToJSON TaxProductResourceTaxRateDetails
data TaxProductResourceTaxRateDetailsFlatAmount'NonNullable
instance Show TaxProductResourceTaxRateDetailsFlatAmount'NonNullable
instance Eq TaxProductResourceTaxRateDetailsFlatAmount'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceTaxRateDetailsFlatAmount'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceTaxRateDetailsFlatAmount'NonNullable
data TaxProductResourceTaxRateDetailsRateType'NonNullable
instance Show TaxProductResourceTaxRateDetailsRateType'NonNullable
instance Eq TaxProductResourceTaxRateDetailsRateType'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceTaxRateDetailsRateType'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceTaxRateDetailsRateType'NonNullable
data TaxProductResourceTaxRateDetailsTaxType'NonNullable
instance Show TaxProductResourceTaxRateDetailsTaxType'NonNullable
instance Eq TaxProductResourceTaxRateDetailsTaxType'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceTaxRateDetailsTaxType'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceTaxRateDetailsTaxType'NonNullable
