module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Show TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Eq TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
