module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
instance Show TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
instance Eq TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTax
