module StripeAPI.Types.TaxProductResourceCustomerDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceCustomerDetails
instance Show TaxProductResourceCustomerDetails
instance Eq TaxProductResourceCustomerDetails
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetails
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetails
data TaxProductResourceCustomerDetailsAddress'NonNullable
instance Show TaxProductResourceCustomerDetailsAddress'NonNullable
instance Eq TaxProductResourceCustomerDetailsAddress'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetailsAddress'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetailsAddress'NonNullable
data TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Show TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Eq TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetailsAddressSource'NonNullable
data TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Show TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Eq TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Data.Aeson.FromJSON TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Data.Aeson.ToJSON TaxProductResourceCustomerDetailsTaxabilityOverride'
