module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsSimplified where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsSimplified
instance Show TaxProductRegistrationsResourceCountryOptionsSimplified
instance Eq TaxProductRegistrationsResourceCountryOptionsSimplified
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsSimplified
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsSimplified
