module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Show TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Eq TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
