module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsEurope where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsEurope
instance Show TaxProductRegistrationsResourceCountryOptionsEurope
instance Eq TaxProductRegistrationsResourceCountryOptionsEurope
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsEurope
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsEurope
data TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Show TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Eq TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsEuropeType'
