module StripeAPI.Types.TaxProductResourceTaxSettingsDefaults where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsDefaults
instance Show TaxProductResourceTaxSettingsDefaults
instance Eq TaxProductResourceTaxSettingsDefaults
instance Data.Aeson.FromJSON TaxProductResourceTaxSettingsDefaults
instance Data.Aeson.ToJSON TaxProductResourceTaxSettingsDefaults
data TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Show TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Eq TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Data.Aeson.FromJSON TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Data.Aeson.ToJSON TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
