module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection
instance Show TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection
instance Eq TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElection
data TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElectionType'
instance Show TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElectionType'
instance Eq TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElectionType'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElectionType'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUsStateSalesTaxElectionType'
