module StripeAPI.Types.TaxProductResourceTaxSettingsHeadOffice where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsHeadOffice
instance Show TaxProductResourceTaxSettingsHeadOffice
instance Eq TaxProductResourceTaxSettingsHeadOffice
instance Data.Aeson.FromJSON TaxProductResourceTaxSettingsHeadOffice
instance Data.Aeson.ToJSON TaxProductResourceTaxSettingsHeadOffice
