module StripeAPI.Types.TaxProductResourceTaxBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxBreakdown
instance Show TaxProductResourceTaxBreakdown
instance Eq TaxProductResourceTaxBreakdown
instance Data.Aeson.FromJSON TaxProductResourceTaxBreakdown
instance Data.Aeson.ToJSON TaxProductResourceTaxBreakdown
data TaxProductResourceTaxBreakdownTaxabilityReason'
instance Show TaxProductResourceTaxBreakdownTaxabilityReason'
instance Eq TaxProductResourceTaxBreakdownTaxabilityReason'
instance Data.Aeson.FromJSON TaxProductResourceTaxBreakdownTaxabilityReason'
instance Data.Aeson.ToJSON TaxProductResourceTaxBreakdownTaxabilityReason'
