module StripeAPI.Types.TaxProductResourceTaxSettingsStatusDetailsResourcePending where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Show TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Eq TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Data.Aeson.FromJSON TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Data.Aeson.ToJSON TaxProductResourceTaxSettingsStatusDetailsResourcePending
