module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsDefault where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsDefault
instance Show TaxProductRegistrationsResourceCountryOptionsDefault
instance Eq TaxProductRegistrationsResourceCountryOptionsDefault
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsDefault
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsDefault
