module StripeAPI.Types.TaxProductResourceTaxSettingsStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsStatusDetails
instance Show TaxProductResourceTaxSettingsStatusDetails
instance Eq TaxProductResourceTaxSettingsStatusDetails
instance Data.Aeson.FromJSON TaxProductResourceTaxSettingsStatusDetails
instance Data.Aeson.ToJSON TaxProductResourceTaxSettingsStatusDetails
