module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsCanada where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsCanada
instance Show TaxProductRegistrationsResourceCountryOptionsCanada
instance Eq TaxProductRegistrationsResourceCountryOptionsCanada
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsCanada
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsCanada
data TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Show TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Eq TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsCanadaType'
