module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsDefaultStandard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsDefaultStandard
instance Show TaxProductRegistrationsResourceCountryOptionsDefaultStandard
instance Eq TaxProductRegistrationsResourceCountryOptionsDefaultStandard
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsDefaultStandard
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsDefaultStandard
data TaxProductRegistrationsResourceCountryOptionsDefaultStandardPlaceOfSupplyScheme'
instance Show TaxProductRegistrationsResourceCountryOptionsDefaultStandardPlaceOfSupplyScheme'
instance Eq TaxProductRegistrationsResourceCountryOptionsDefaultStandardPlaceOfSupplyScheme'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsDefaultStandardPlaceOfSupplyScheme'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsDefaultStandardPlaceOfSupplyScheme'
