module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsEuStandard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Show TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Eq TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsEuStandard
data TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Show TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Eq TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
