module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptions
instance Show TaxProductRegistrationsResourceCountryOptions
instance Eq TaxProductRegistrationsResourceCountryOptions
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptions
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptions
