module StripeAPI.Types.TaxProductResourceLineItemTaxRateDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceLineItemTaxRateDetails
instance Show TaxProductResourceLineItemTaxRateDetails
instance Eq TaxProductResourceLineItemTaxRateDetails
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxRateDetails
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxRateDetails
data TaxProductResourceLineItemTaxRateDetailsTaxType'
instance Show TaxProductResourceLineItemTaxRateDetailsTaxType'
instance Eq TaxProductResourceLineItemTaxRateDetailsTaxType'
instance Data.Aeson.FromJSON TaxProductResourceLineItemTaxRateDetailsTaxType'
instance Data.Aeson.ToJSON TaxProductResourceLineItemTaxRateDetailsTaxType'
