module StripeAPI.Types.TaxProductResourceTaxCalculationShippingCost where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxCalculationShippingCost
instance Show TaxProductResourceTaxCalculationShippingCost
instance Eq TaxProductResourceTaxCalculationShippingCost
instance Data.Aeson.FromJSON TaxProductResourceTaxCalculationShippingCost
instance Data.Aeson.ToJSON TaxProductResourceTaxCalculationShippingCost
data TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Show TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Eq TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Data.Aeson.FromJSON TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Data.Aeson.ToJSON TaxProductResourceTaxCalculationShippingCostTaxBehavior'
