module StripeAPI.Types.TaxProductResourceTaxTransactionShippingCost where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionShippingCost
instance Show TaxProductResourceTaxTransactionShippingCost
instance Eq TaxProductResourceTaxTransactionShippingCost
instance Data.Aeson.FromJSON TaxProductResourceTaxTransactionShippingCost
instance Data.Aeson.ToJSON TaxProductResourceTaxTransactionShippingCost
data TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Show TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Eq TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Data.Aeson.FromJSON TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Data.Aeson.ToJSON TaxProductResourceTaxTransactionShippingCostTaxBehavior'
