module StripeAPI.Types.TaxProductResourceTaxTransactionResourceReversal where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionResourceReversal
instance Show TaxProductResourceTaxTransactionResourceReversal
instance Eq TaxProductResourceTaxTransactionResourceReversal
instance Data.Aeson.FromJSON TaxProductResourceTaxTransactionResourceReversal
instance Data.Aeson.ToJSON TaxProductResourceTaxTransactionResourceReversal
