module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUnitedStates where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Show TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Eq TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUnitedStates
data TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Show TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Eq TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Data.Aeson.FromJSON TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Data.Aeson.ToJSON TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
