module StripeAPI.Types.TerminalReaderReaderResourceCollectPaymentMethodAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceCollectPaymentMethodAction
instance Show TerminalReaderReaderResourceCollectPaymentMethodAction
instance Eq TerminalReaderReaderResourceCollectPaymentMethodAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceCollectPaymentMethodAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceCollectPaymentMethodAction
data TerminalReaderReaderResourceCollectPaymentMethodActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceCollectPaymentMethodActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceCollectPaymentMethodActionPaymentIntent'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceCollectPaymentMethodActionPaymentIntent'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceCollectPaymentMethodActionPaymentIntent'Variants
