module StripeAPI.Types.TerminalReaderReaderResourceLineItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceLineItem
instance Show TerminalReaderReaderResourceLineItem
instance Eq TerminalReaderReaderResourceLineItem
instance Data.Aeson.FromJSON TerminalReaderReaderResourceLineItem
instance Data.Aeson.ToJSON TerminalReaderReaderResourceLineItem
