module StripeAPI.Types.TerminalReaderReaderResourceRefundPaymentAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceRefundPaymentAction
instance Show TerminalReaderReaderResourceRefundPaymentAction
instance Eq TerminalReaderReaderResourceRefundPaymentAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceRefundPaymentAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceRefundPaymentAction
data TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
data TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
data TerminalReaderReaderResourceRefundPaymentActionReason'
instance Show TerminalReaderReaderResourceRefundPaymentActionReason'
instance Eq TerminalReaderReaderResourceRefundPaymentActionReason'
instance Data.Aeson.FromJSON TerminalReaderReaderResourceRefundPaymentActionReason'
instance Data.Aeson.ToJSON TerminalReaderReaderResourceRefundPaymentActionReason'
data TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
