module StripeAPI.Types.TerminalConfigurationConfigurationResourceOfflineConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceOfflineConfig
instance Show TerminalConfigurationConfigurationResourceOfflineConfig
instance Eq TerminalConfigurationConfigurationResourceOfflineConfig
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceOfflineConfig
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceOfflineConfig
