module StripeAPI.Types.TerminalReaderReaderResourceProcessPaymentIntentAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceProcessPaymentIntentAction
instance Show TerminalReaderReaderResourceProcessPaymentIntentAction
instance Eq TerminalReaderReaderResourceProcessPaymentIntentAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceProcessPaymentIntentAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceProcessPaymentIntentAction
data TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
