module StripeAPI.Types.TerminalConfigurationConfigurationResourceRebootWindow where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceRebootWindow
instance Show TerminalConfigurationConfigurationResourceRebootWindow
instance Eq TerminalConfigurationConfigurationResourceRebootWindow
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceRebootWindow
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceRebootWindow
