module StripeAPI.Types.TerminalReaderReaderResourceConfirmPaymentIntentAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceConfirmPaymentIntentAction
instance Show TerminalReaderReaderResourceConfirmPaymentIntentAction
instance Eq TerminalReaderReaderResourceConfirmPaymentIntentAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceConfirmPaymentIntentAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceConfirmPaymentIntentAction
data TerminalReaderReaderResourceConfirmPaymentIntentActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceConfirmPaymentIntentActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceConfirmPaymentIntentActionPaymentIntent'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceConfirmPaymentIntentActionPaymentIntent'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceConfirmPaymentIntentActionPaymentIntent'Variants
