module StripeAPI.Types.TerminalConfigurationConfigurationResourceEnterpriseTlsWifi where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceEnterpriseTlsWifi
instance Show TerminalConfigurationConfigurationResourceEnterpriseTlsWifi
instance Eq TerminalConfigurationConfigurationResourceEnterpriseTlsWifi
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceEnterpriseTlsWifi
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceEnterpriseTlsWifi
