module StripeAPI.Types.TerminalReaderReaderResourceSetReaderDisplayAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceSetReaderDisplayAction
instance Show TerminalReaderReaderResourceSetReaderDisplayAction
instance Eq TerminalReaderReaderResourceSetReaderDisplayAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceSetReaderDisplayAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceSetReaderDisplayAction
data TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Show TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Eq TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Data.Aeson.FromJSON TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Data.Aeson.ToJSON TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
