module StripeAPI.Types.TerminalConfigurationConfigurationResourceWifiConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceWifiConfig
instance Show TerminalConfigurationConfigurationResourceWifiConfig
instance Eq TerminalConfigurationConfigurationResourceWifiConfig
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceWifiConfig
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceWifiConfig
data TerminalConfigurationConfigurationResourceWifiConfigType'
instance Show TerminalConfigurationConfigurationResourceWifiConfigType'
instance Eq TerminalConfigurationConfigurationResourceWifiConfigType'
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceWifiConfigType'
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceWifiConfigType'
