module StripeAPI.Types.TerminalReaderReaderResourceToggle where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceToggle
instance Show TerminalReaderReaderResourceToggle
instance Eq TerminalReaderReaderResourceToggle
instance Data.Aeson.FromJSON TerminalReaderReaderResourceToggle
instance Data.Aeson.ToJSON TerminalReaderReaderResourceToggle
data TerminalReaderReaderResourceToggleDefaultValue'NonNullable
instance Show TerminalReaderReaderResourceToggleDefaultValue'NonNullable
instance Eq TerminalReaderReaderResourceToggleDefaultValue'NonNullable
instance Data.Aeson.FromJSON TerminalReaderReaderResourceToggleDefaultValue'NonNullable
instance Data.Aeson.ToJSON TerminalReaderReaderResourceToggleDefaultValue'NonNullable
data TerminalReaderReaderResourceToggleValue'NonNullable
instance Show TerminalReaderReaderResourceToggleValue'NonNullable
instance Eq TerminalReaderReaderResourceToggleValue'NonNullable
instance Data.Aeson.FromJSON TerminalReaderReaderResourceToggleValue'NonNullable
instance Data.Aeson.ToJSON TerminalReaderReaderResourceToggleValue'NonNullable
