module StripeAPI.Types.TerminalReaderReaderResourceCart where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceCart
instance Show TerminalReaderReaderResourceCart
instance Eq TerminalReaderReaderResourceCart
instance Data.Aeson.FromJSON TerminalReaderReaderResourceCart
instance Data.Aeson.ToJSON TerminalReaderReaderResourceCart
