module StripeAPI.Types.TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Show TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Eq TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
data TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Show TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Eq TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
