module StripeAPI.Types.TerminalConfigurationConfigurationResourceTipping where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceTipping
instance Show TerminalConfigurationConfigurationResourceTipping
instance Eq TerminalConfigurationConfigurationResourceTipping
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceTipping
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceTipping
