module StripeAPI.Types.TerminalReaderReaderResourceProcessSetupIntentAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceProcessSetupIntentAction
instance Show TerminalReaderReaderResourceProcessSetupIntentAction
instance Eq TerminalReaderReaderResourceProcessSetupIntentAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceProcessSetupIntentAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceProcessSetupIntentAction
data TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Show TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Eq TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Data.Aeson.FromJSON TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Data.Aeson.ToJSON TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
