module StripeAPI.Types.TerminalConfigurationConfigurationResourceCurrencySpecificConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Show TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Eq TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceCurrencySpecificConfig
