module StripeAPI.Types.TerminalConfigurationConfigurationResourcePersonalPskWifi where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourcePersonalPskWifi
instance Show TerminalConfigurationConfigurationResourcePersonalPskWifi
instance Eq TerminalConfigurationConfigurationResourcePersonalPskWifi
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourcePersonalPskWifi
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourcePersonalPskWifi
