module StripeAPI.Types.TerminalReaderReaderResourceProcessConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceProcessConfig
instance Show TerminalReaderReaderResourceProcessConfig
instance Eq TerminalReaderReaderResourceProcessConfig
instance Data.Aeson.FromJSON TerminalReaderReaderResourceProcessConfig
instance Data.Aeson.ToJSON TerminalReaderReaderResourceProcessConfig
