module StripeAPI.Types.TerminalReaderReaderResourceReaderAction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceReaderAction
instance Show TerminalReaderReaderResourceReaderAction
instance Eq TerminalReaderReaderResourceReaderAction
instance Data.Aeson.FromJSON TerminalReaderReaderResourceReaderAction
instance Data.Aeson.ToJSON TerminalReaderReaderResourceReaderAction
data TerminalReaderReaderResourceReaderActionStatus'
instance Show TerminalReaderReaderResourceReaderActionStatus'
instance Eq TerminalReaderReaderResourceReaderActionStatus'
instance Data.Aeson.FromJSON TerminalReaderReaderResourceReaderActionStatus'
instance Data.Aeson.ToJSON TerminalReaderReaderResourceReaderActionStatus'
data TerminalReaderReaderResourceReaderActionType'
instance Show TerminalReaderReaderResourceReaderActionType'
instance Eq TerminalReaderReaderResourceReaderActionType'
instance Data.Aeson.FromJSON TerminalReaderReaderResourceReaderActionType'
instance Data.Aeson.ToJSON TerminalReaderReaderResourceReaderActionType'
