module StripeAPI.Types.TerminalConfigurationConfigurationResourceEnterprisePeapWifi where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceEnterprisePeapWifi
instance Show TerminalConfigurationConfigurationResourceEnterprisePeapWifi
instance Eq TerminalConfigurationConfigurationResourceEnterprisePeapWifi
instance Data.Aeson.FromJSON TerminalConfigurationConfigurationResourceEnterprisePeapWifi
instance Data.Aeson.ToJSON TerminalConfigurationConfigurationResourceEnterprisePeapWifi
