module StripeAPI.Types.TerminalReaderReaderResourceTippingConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TerminalReaderReaderResourceTippingConfig
instance Show TerminalReaderReaderResourceTippingConfig
instance Eq TerminalReaderReaderResourceTippingConfig
instance Data.Aeson.FromJSON TerminalReaderReaderResourceTippingConfig
instance Data.Aeson.ToJSON TerminalReaderReaderResourceTippingConfig
