module StripeAPI.Types.ThresholdsResourceUsageAlertFilter where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ThresholdsResourceUsageAlertFilter
instance Show ThresholdsResourceUsageAlertFilter
instance Eq ThresholdsResourceUsageAlertFilter
instance Data.Aeson.FromJSON ThresholdsResourceUsageAlertFilter
instance Data.Aeson.ToJSON ThresholdsResourceUsageAlertFilter
data ThresholdsResourceUsageAlertFilterCustomer'NonNullableVariants
instance Show ThresholdsResourceUsageAlertFilterCustomer'NonNullableVariants
instance Eq ThresholdsResourceUsageAlertFilterCustomer'NonNullableVariants
instance Data.Aeson.FromJSON ThresholdsResourceUsageAlertFilterCustomer'NonNullableVariants
instance Data.Aeson.ToJSON ThresholdsResourceUsageAlertFilterCustomer'NonNullableVariants
