module StripeAPI.Types.ThresholdsResourceUsageThresholdConfig where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ThresholdsResourceUsageThresholdConfig
instance Show ThresholdsResourceUsageThresholdConfig
instance Eq ThresholdsResourceUsageThresholdConfig
instance Data.Aeson.FromJSON ThresholdsResourceUsageThresholdConfig
instance Data.Aeson.ToJSON ThresholdsResourceUsageThresholdConfig
data ThresholdsResourceUsageThresholdConfigMeter'Variants
instance Show ThresholdsResourceUsageThresholdConfigMeter'Variants
instance Eq ThresholdsResourceUsageThresholdConfigMeter'Variants
instance Data.Aeson.FromJSON ThresholdsResourceUsageThresholdConfigMeter'Variants
instance Data.Aeson.ToJSON ThresholdsResourceUsageThresholdConfigMeter'Variants
