module StripeAPI.Types.Treasury_FinancialAccountFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data Treasury'financialAccountFeatures
instance Show Treasury'financialAccountFeatures
instance Eq Treasury'financialAccountFeatures
instance Data.Aeson.FromJSON Treasury'financialAccountFeatures
instance Data.Aeson.ToJSON Treasury'financialAccountFeatures
