module StripeAPI.Types.TreasuryFinancialAccountsResourceTogglesSettingStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
