module StripeAPI.Types.TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Data.Aeson.FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Data.Aeson.ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Data.Aeson.FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Data.Aeson.ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Data.Aeson.FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Data.Aeson.ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
