module StripeAPI.Types.TreasuryReceivedDebitsResourceLinkedFlows where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceLinkedFlows
instance Show TreasuryReceivedDebitsResourceLinkedFlows
instance Eq TreasuryReceivedDebitsResourceLinkedFlows
instance Data.Aeson.FromJSON TreasuryReceivedDebitsResourceLinkedFlows
instance Data.Aeson.ToJSON TreasuryReceivedDebitsResourceLinkedFlows
