module StripeAPI.Types.TreasuryInboundTransfersResourceFailureDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceFailureDetails
instance Show TreasuryInboundTransfersResourceFailureDetails
instance Eq TreasuryInboundTransfersResourceFailureDetails
instance Data.Aeson.FromJSON TreasuryInboundTransfersResourceFailureDetails
instance Data.Aeson.ToJSON TreasuryInboundTransfersResourceFailureDetails
data TreasuryInboundTransfersResourceFailureDetailsCode'
instance Show TreasuryInboundTransfersResourceFailureDetailsCode'
instance Eq TreasuryInboundTransfersResourceFailureDetailsCode'
instance Data.Aeson.FromJSON TreasuryInboundTransfersResourceFailureDetailsCode'
instance Data.Aeson.ToJSON TreasuryInboundTransfersResourceFailureDetailsCode'
