module StripeAPI.Types.TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetails
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetailsType'
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetailsType'
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetailsType'
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetailsType'
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceTrackingDetailsType'
