module StripeAPI.Types.TreasuryFinancialAccountsResourcePlatformRestrictions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourcePlatformRestrictions
instance Show TreasuryFinancialAccountsResourcePlatformRestrictions
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictions
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourcePlatformRestrictions
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourcePlatformRestrictions
data TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Show TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
data TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Show TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
