module StripeAPI.Types.TreasuryFinancialAccountsResourceAbaToggleSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceAbaToggleSettings
instance Show TreasuryFinancialAccountsResourceAbaToggleSettings
instance Eq TreasuryFinancialAccountsResourceAbaToggleSettings
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceAbaToggleSettings
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceAbaToggleSettings
data TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
