module StripeAPI.Types.TreasuryTransactionsResourceBalanceImpact where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryTransactionsResourceBalanceImpact
instance Show TreasuryTransactionsResourceBalanceImpact
instance Eq TreasuryTransactionsResourceBalanceImpact
instance Data.Aeson.FromJSON TreasuryTransactionsResourceBalanceImpact
instance Data.Aeson.ToJSON TreasuryTransactionsResourceBalanceImpact
