module StripeAPI.Types.TreasuryOutboundTransfersResourceAchTrackingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceAchTrackingDetails
instance Show TreasuryOutboundTransfersResourceAchTrackingDetails
instance Eq TreasuryOutboundTransfersResourceAchTrackingDetails
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceAchTrackingDetails
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceAchTrackingDetails
