module StripeAPI.Types.TreasuryTransactionsResourceFlowDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryTransactionsResourceFlowDetails
instance Show TreasuryTransactionsResourceFlowDetails
instance Eq TreasuryTransactionsResourceFlowDetails
instance Data.Aeson.FromJSON TreasuryTransactionsResourceFlowDetails
instance Data.Aeson.ToJSON TreasuryTransactionsResourceFlowDetails
data TreasuryTransactionsResourceFlowDetailsType'
instance Show TreasuryTransactionsResourceFlowDetailsType'
instance Eq TreasuryTransactionsResourceFlowDetailsType'
instance Data.Aeson.FromJSON TreasuryTransactionsResourceFlowDetailsType'
instance Data.Aeson.ToJSON TreasuryTransactionsResourceFlowDetailsType'
