module StripeAPI.Types.TreasuryReceivedCreditsResourceReversalDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceReversalDetails
instance Show TreasuryReceivedCreditsResourceReversalDetails
instance Eq TreasuryReceivedCreditsResourceReversalDetails
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceReversalDetails
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceReversalDetails
data TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Show TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Eq TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
