module StripeAPI.Types.TreasuryReceivedDebitsResourceDebitReversalLinkedFlows where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceDebitReversalLinkedFlows
instance Show TreasuryReceivedDebitsResourceDebitReversalLinkedFlows
instance Eq TreasuryReceivedDebitsResourceDebitReversalLinkedFlows
instance Data.Aeson.FromJSON TreasuryReceivedDebitsResourceDebitReversalLinkedFlows
instance Data.Aeson.ToJSON TreasuryReceivedDebitsResourceDebitReversalLinkedFlows
