module StripeAPI.Types.TreasurySharedResourceBillingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasurySharedResourceBillingDetails
instance Show TreasurySharedResourceBillingDetails
instance Eq TreasurySharedResourceBillingDetails
instance Data.Aeson.FromJSON TreasurySharedResourceBillingDetails
instance Data.Aeson.ToJSON TreasurySharedResourceBillingDetails
