module StripeAPI.Types.TreasuryFinancialAccountsResourceToggleSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceToggleSettings
instance Show TreasuryFinancialAccountsResourceToggleSettings
instance Eq TreasuryFinancialAccountsResourceToggleSettings
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceToggleSettings
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceToggleSettings
data TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceToggleSettingsStatus'
