module StripeAPI.Types.TreasuryOutboundPaymentsResourceReturnedStatus where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceReturnedStatus
instance Show TreasuryOutboundPaymentsResourceReturnedStatus
instance Eq TreasuryOutboundPaymentsResourceReturnedStatus
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceReturnedStatus
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceReturnedStatus
data TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Show TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Eq TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceReturnedStatusCode'
data TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Show TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Eq TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
