module StripeAPI.Types.TreasuryFinancialAccountsResourceInboundTransfers where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceInboundTransfers
instance Show TreasuryFinancialAccountsResourceInboundTransfers
instance Eq TreasuryFinancialAccountsResourceInboundTransfers
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceInboundTransfers
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceInboundTransfers
