module StripeAPI.Types.TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails
instance Show TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails
instance Eq TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceUsDomesticWireTrackingDetails
