module StripeAPI.Types.TreasuryOutboundTransfersResourceReturnedDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceReturnedDetails
instance Show TreasuryOutboundTransfersResourceReturnedDetails
instance Eq TreasuryOutboundTransfersResourceReturnedDetails
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceReturnedDetails
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceReturnedDetails
data TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Show TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Eq TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceReturnedDetailsCode'
data TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Show TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Eq TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
