module StripeAPI.Types.TreasuryReceivedCreditsResourceSourceFlowsDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Show TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Eq TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceSourceFlowsDetails
data TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Show TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Eq TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
