module StripeAPI.Types.TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
