module StripeAPI.Types.TreasuryReceivedDebitsResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceStatusTransitions
instance Show TreasuryReceivedDebitsResourceStatusTransitions
instance Eq TreasuryReceivedDebitsResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryReceivedDebitsResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryReceivedDebitsResourceStatusTransitions
