module StripeAPI.Types.TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Show TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Eq TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Data.Aeson.FromJSON TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Data.Aeson.ToJSON TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
