module StripeAPI.Types.TreasuryReceivedCreditsResourceLinkedFlows where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceLinkedFlows
instance Show TreasuryReceivedCreditsResourceLinkedFlows
instance Eq TreasuryReceivedCreditsResourceLinkedFlows
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceLinkedFlows
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceLinkedFlows
data TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Show TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Eq TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
data TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Show TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Eq TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
