module StripeAPI.Types.TreasuryReceivedCreditsResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceStatusTransitions
instance Show TreasuryReceivedCreditsResourceStatusTransitions
instance Eq TreasuryReceivedCreditsResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryReceivedCreditsResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryReceivedCreditsResourceStatusTransitions
