module StripeAPI.Types.TreasuryFinancialAccountsResourceFinancialAddressesFeatures where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Show TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Eq TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceFinancialAddressesFeatures
