module StripeAPI.Types.TreasuryReceivedDebitsResourceReversalDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceReversalDetails
instance Show TreasuryReceivedDebitsResourceReversalDetails
instance Eq TreasuryReceivedDebitsResourceReversalDetails
instance Data.Aeson.FromJSON TreasuryReceivedDebitsResourceReversalDetails
instance Data.Aeson.ToJSON TreasuryReceivedDebitsResourceReversalDetails
data TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Show TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Eq TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Data.Aeson.FromJSON TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Data.Aeson.ToJSON TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
