module StripeAPI.Types.TreasuryFinancialAccountsResourceStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceStatusDetails
instance Show TreasuryFinancialAccountsResourceStatusDetails
instance Eq TreasuryFinancialAccountsResourceStatusDetails
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceStatusDetails
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceStatusDetails
data TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Show TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Eq TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
data TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Show TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Eq TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
