module StripeAPI.Types.TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails
instance Show TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails
instance Eq TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetails
data TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetailsType'
instance Show TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetailsType'
instance Eq TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetailsType'
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetailsType'
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceOutboundTransferResourceTrackingDetailsType'
