module StripeAPI.Types.TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails
instance Show TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails
instance Eq TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceUsDomesticWireTrackingDetails
