module StripeAPI.Types.TreasuryFinancialAccountsResourceOutboundPayments where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceOutboundPayments
instance Show TreasuryFinancialAccountsResourceOutboundPayments
instance Eq TreasuryFinancialAccountsResourceOutboundPayments
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceOutboundPayments
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceOutboundPayments
