module StripeAPI.Types.TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Show TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Eq TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
