module StripeAPI.Types.TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Data.Aeson.FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Data.Aeson.ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
