module StripeAPI.Types.TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Data.Aeson.FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Data.Aeson.ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
