module StripeAPI.Types.TreasuryFinancialAccountsResourceInboundAchToggleSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceInboundAchToggleSettings
instance Show TreasuryFinancialAccountsResourceInboundAchToggleSettings
instance Eq TreasuryFinancialAccountsResourceInboundAchToggleSettings
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceInboundAchToggleSettings
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceInboundAchToggleSettings
data TreasuryFinancialAccountsResourceInboundAchToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceInboundAchToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceInboundAchToggleSettingsStatus'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceInboundAchToggleSettingsStatus'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceInboundAchToggleSettingsStatus'
