module StripeAPI.Types.TreasuryFinancialAccountsResourceOutboundTransfers where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceOutboundTransfers
instance Show TreasuryFinancialAccountsResourceOutboundTransfers
instance Eq TreasuryFinancialAccountsResourceOutboundTransfers
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceOutboundTransfers
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceOutboundTransfers
