module StripeAPI.Types.TreasuryFinancialAccountsResourceFinancialAddress where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceFinancialAddress
instance Show TreasuryFinancialAccountsResourceFinancialAddress
instance Eq TreasuryFinancialAccountsResourceFinancialAddress
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceFinancialAddress
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceFinancialAddress
data TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Show TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Eq TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
