module StripeAPI.Types.TreasuryFinancialAccountsResourceBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceBalance
instance Show TreasuryFinancialAccountsResourceBalance
instance Eq TreasuryFinancialAccountsResourceBalance
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceBalance
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceBalance
