module StripeAPI.Types.TreasuryFinancialAccountsResourceClosedStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceClosedStatusDetails
instance Show TreasuryFinancialAccountsResourceClosedStatusDetails
instance Eq TreasuryFinancialAccountsResourceClosedStatusDetails
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceClosedStatusDetails
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceClosedStatusDetails
data TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Show TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Eq TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
