module StripeAPI.Types.TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Show TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Eq TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
