module StripeAPI.Types.TreasuryOutboundTransfersResourceStatusTransitions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceStatusTransitions
instance Show TreasuryOutboundTransfersResourceStatusTransitions
instance Eq TreasuryOutboundTransfersResourceStatusTransitions
instance Data.Aeson.FromJSON TreasuryOutboundTransfersResourceStatusTransitions
instance Data.Aeson.ToJSON TreasuryOutboundTransfersResourceStatusTransitions
