module StripeAPI.Types.TreasuryFinancialAccountsResourceOutboundAchToggleSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceOutboundAchToggleSettings
instance Show TreasuryFinancialAccountsResourceOutboundAchToggleSettings
instance Eq TreasuryFinancialAccountsResourceOutboundAchToggleSettings
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceOutboundAchToggleSettings
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceOutboundAchToggleSettings
data TreasuryFinancialAccountsResourceOutboundAchToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceOutboundAchToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceOutboundAchToggleSettingsStatus'
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceOutboundAchToggleSettingsStatus'
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceOutboundAchToggleSettingsStatus'
