module StripeAPI.Types.TreasuryFinancialAccountsResourceAbaRecord where
import qualified Data.Aeson
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceAbaRecord
instance Show TreasuryFinancialAccountsResourceAbaRecord
instance Eq TreasuryFinancialAccountsResourceAbaRecord
instance Data.Aeson.FromJSON TreasuryFinancialAccountsResourceAbaRecord
instance Data.Aeson.ToJSON TreasuryFinancialAccountsResourceAbaRecord
